configuration: Release
platform: x64

image:
  - Visual Studio 2019
  
cache:
  - packages -> **\packages.config

before_build:
  - git submodule update --init --recursive --remote
  - nuget restore PaisleyPark.sln
  - nuget restore lib/Nhaama.FFXIV/Nhaama.FFXIV.csproj
  - nuget restore lib/Nhaama.Memory/Nhaama.Memory.csproj
  - ps: Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
  
build:
  project: PaisleyPark.sln
  
artifacts:
  - path: PaisleyPark\bin\x64\Release\PaisleyPark.zip
    name: PaisleyPark

deploy:
  tag: $(appveyor_repo_tag_name)
  release: Paisley Park $(appveyor_repo_tag_name)
  provider: GitHub
  draft: true
  auth_token:
    secure: O6Rsj+hoS5X7Q1u7TjtFwjRN53ohwjF8Mik/BpVidoefAag5FfpxoWqS5GTdJECG
  artifact: PaisleyPark
  on:
    branch: master
    appveyor_repo_tag: true
